apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: boats.codershangfeng.github.com
spec:
  group: codershangfeng.github.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                image:
                  type: string
  scope: Namespaced
  names:
    plural: boats
    singular: boat
    kind: Boat
    shortNames:
    - b
